dist: xenial
language: java

addons:
  sonarcloud:
    organization: "lukasbach-github"
    token:
      secure: "qOvgagzq/KsRrDH1xZHKhao6fQBApzgcdZXBetgbMu2DEgiFaGiCPcbtWhnJw4mxyGeM2QVD/Bo5k/dR9ELh6Wg/j6SsVoxmIsFiBFCD+GVSPBPuorO3ORXKtSvQSW5Jqx1186vK0iNAlyI/Iyt0n1s7WM/u+DIOeN2tB+KCWeabke8USBdc9cnAEtjnXKvyOzQvTzRL1Rv/+UcSuqTeuxE7B5KDKoQaTOzQQe0AH+pAiFR2SAGqVpEl1XhPbqhnMBe7d/kTtcqeIu8nL8ld2KAGVRNcWoWrr0fSX+pu1TX4/OeKWiZ6/buHoxwzrPPGyHFLCxwmVJ4BCa70wY5gBtmSLquub/xoiIvzroJB6yffpv8lwMC4hm8EVZviUO0hUno/dqdaS9U2jenYckbZaZssFwMTI5ROK2KzZfS240+HRNBNkXulQd/JzNP8+9vWpVTZAN94+5ggVyhN01DiT/npQes4SO5GsCmliABl1kjU4hMK+IBsNADYvdbHKmHiOIbCGNGkIEBCwcO3MAwCj00hSEm/uhJhgAfGRV6Gx0xSZQXX99nL8AArhBkeovp+bc50SXZ6hD3/MZ5Joe6lTT98JVspH0A6uDZE/T3jcTp1e7dBxNdcHpPgNiGY09naFp3VHzP3FcK9lI+2l76ppWKLoxThMGb5GtmZAeKKIDQ="

os: linux
jdk: openjdk11
env: DISPLAY=:99.0 # tests need a display to test against
install: true

services:
  - xvfb # tests need virtual framebuffer to test against

cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'

before_install:
- git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
- ". /tmp/BuildUtilities/travis-ci/setupenvironment.sh"

script:
  # Build, run tests and generate binary jacoco output
  - mvn clean install test verify

  # Download Jacoco CLI
  - curl https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.5/org.jacoco.cli-0.8.5-nodeps.jar --output jacococli.jar
  
  # Generate jacoco XML reports from binary output
  - java -jar jacococli.jar report tests/edu.kit.textannotation.annotationplugin.tests/target/coverage-reports/jacoco.exec --classfiles bundles/edu.kit.textannotation.annotationplugin/target/classes --html $HOME/coverage --xml $HOME/jacoco.xml

  # Run sonar scanner
  - mvn sonar:sonar -Dsonar.projectKey=lukasbach_textannotation -Dsonar.java.source=1.8 -Dsonar.coverage.jacoco.xmlReportPaths=$HOME/jacoco.xml -Dsonar.junit.reportPaths=target/surefire-reports
